name: ci

on:
  push:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # remove on 2/13/22 when 18 is default
      - name: setup node-18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install libkrb # only for nodegit
        run: sudo apt-get install libkrb5-dev -y
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: get pnpm store path
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-store-
      - name: install pnpm deps
        run: pnpm install
      - name: setup just
        uses: extractions/setup-just@v1
      - name: compile
        run: just compile
      - name: test
        run: just test
      - name: typecheck
        run: just typecheck
      - name: format
        run: just format
      - name: lint
        run: just lint
